// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxfiqqzrdrmsddzksmec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZmlxcXpyZHJtc2RkemtzbWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTAwODksImV4cCI6MjA2NTg4NjA4OX0.lmNqegtQi_wI1qT4iSSuww2zHAG7aWZtvUebcvlwMmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);